Implement photos tag search
nextcloud/photos pull request #1062
Opened 2022-03-22 12:02 UTC by marcelklehr

This implements tag search in photos directly, until https://github.com/nextcloud/server/pull/26813 is merged.

2022-03-22 13:29 UTC, Mikescops requested changes

2022-03-22 13:29 UTC, Mikescops commented on package.json
> +		"lodash": "^4.17.21",
Please refer to this documentation to avoid using lodash: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore

2022-03-22 13:29 UTC, Mikescops commented on src/views/Timeline.vue
> +				clearTimeout(this.searchTimeout)
you probably have to clearTimeout on component dismount too

2022-03-22 13:29 UTC, Mikescops commented on src/views/Timeline.vue
> +				await Promise.all(uniqueTags.map(tagId =>
shall we add a try/catch here?

2022-06-10 16:33 UTC, marcelklehr commented
/compile amend /

2022-06-10 16:35 UTC, marcelklehr commented
https://github.com/nextcloud/server/pull/26813 is merged now, but this is still nice to have, I think

2022-06-10 17:12 UTC, Mikescops approved these changes
Sounds great

2022-12-31 23:16 UTC, LovelyA72 commented
Any update on this pr? This is a very useful feature when having a lot of tags.

2023-01-01 09:35 UTC, marcelklehr commented
This PR likely needs a rewrite since the photos 2.0 changes

2025-01-07 08:55 UTC, closed without merging