All collaborators management views
nextcloud/photos pull request #1161
Opened 2022-08-24 11:25 UTC by artonge

2022-08-25 16:53 UTC, jancborchardt requested changes
Looks good, just a few things:
- [ ] The "Share link" finction looks oddly placed and not interactive. Maybe better as a secondary button on the bottom left instead?
- [ ] The gab below the input field looks off. Wouldn't this work like in Files, where people are picked one by one from the suggestion dropdown?
- [ ] Possibly a general Vue component thing, but there should be a close x within the modal on the top right
- [ ] Wording in the title subline: "users" to "people", and " group" needs to be plural "groups"

2022-08-31 17:55 UTC, nimishavijay commented
Looks very nice! Agree with everything mentioned, plus a few more points:
- "Save collaborators list" --> "Save" or maybe "Save collaborators"
- Usually the icon associated with "Save" is the checkmark icon. The paper plane icon is usually for send. I'm also wondering if we need an icon at all 
- "Share this album via link" --> "Share via public link"? To make it clearer that it's a public link and to make it shorter if it's going to be a button on the bottom left
- We can also add an icon to the "Share via public link" button as when it's clicked it changes into the "Copy link" button which has an icon 
- Maybe there can also be a way to unshare in case the "Share via public link" button was clicked by accident. If we are going with the secondary button on the bottom left, then there could possibly be:
  - a trash icon or close icon next to it on the right which would unshare
  - or a 3 dot menu with one item "Unshare"

cc @jancborchardt as well

2022-09-13 10:39 UTC, skjnldsv commented
Please rebase after #1228

2022-09-15 06:09 UTC, skjnldsv approved these changes

2022-09-15 10:26 UTC, artonge commented on lib/Controller/PreviewController.php
> +class PreviewController extends Controller {
`OC\Core\Controller\PreviewController` is not public

2022-09-15 10:36 UTC, artonge commented on src/components/Albums/CollaboratorsSelectionForm.vue
> +				const response = await axios.get(generateOcsUrl('core/autocomplete/get'), {
What about `enable_share_accept` ?

2022-09-15 11:37 UTC, artonge commented on src/components/Albums/CollaboratorsSelectionForm.vue
> +				const response = await axios.get(generateOcsUrl('core/autocomplete/get'), {
- If the `files_sharing` app is not enabled, I hide any buttons showing to `CollaboratorsSelectionForm`
- I added support to `sharing.minSearchStringLength` in `CollaboratorsSelectionForm`

2022-09-15 11:40 UTC, artonge commented on src/services/PhotoSearch.js
> +	// .map(data => ({ ...data, filename: data.filename.replace(prefixPath, '') }))
Cleaned

2022-09-15 12:19 UTC, skjnldsv commented on lib/Controller/PreviewController.php
> +class PreviewController extends Controller {
Well, I think we should do it anyway :)

2022-09-15 16:09 UTC, PVince81 approved these changes
Reviewed together, looks good :+1:

the only critical part I think is the DB schema to remove the cached display name and use the display name cache instead / lazy user

2022-09-15 16:11 UTC, PVince81 commented
for retrieving display names, use `$this->userManager->getDisplayName($userId)` to make sure it hits the cache

2022-09-16 07:40 UTC, artonge commented on lib/Album/AlbumMapper.php
> +				'label' => $collaborator->getDisplayName(),
Actually, I don't cache the displayName in the DB

2022-09-16 07:41 UTC, artonge commented
/compile amend /

2022-09-16 07:57 UTC, merged