fix service-worker
nextcloud/photos pull request #1204
Opened 2022-09-03 18:28 UTC by szaimen

Found via https://github.com/search?q=org%3Anextcloud+noRewrite&type=code

Disclaimer: I wasn't able to test this but I think it should work.

Signed-off-by: szaimen <szaimen@e.mail.de>

2022-09-03 18:45 UTC, szaimen commented on src/Photos.vue
> +					noRewrite: doesURLContainIndexPHP,
```suggestion
					noRewrite: !doesURLContainIndexPHP,
```
we may need to invert the logic here to make it work. not sure though...

2022-09-03 18:46 UTC, szaimen commented on src/Photos.vue
> +					noRewrite: doesURLContainIndexPHP,
or we simply always set it to true, WDYT?

2022-09-04 00:33 UTC, szaimen commented on src/Photos.vue
> +					noRewrite: doesURLContainIndexPHP,
done

2022-09-06 08:10 UTC, artonge approved these changes

2022-09-06 08:36 UTC, skjnldsv requested changes
Let's wait for #1206

2022-09-06 08:42 UTC, skjnldsv commented
/rebase

2022-09-06 08:45 UTC, skjnldsv commented
/compile amend /

2022-09-06 08:45 UTC, skjnldsv approved these changes

2022-09-06 08:57 UTC, merged

2022-09-07 14:08 UTC, szaimen commented
/backport to stable24

2022-09-07 14:08 UTC, szaimen commented
/backport to stable23