Make sure we have a valid fileID for albums content
nextcloud/photos pull request #1279
Opened 2022-09-22 06:27 UTC by skjnldsv

Signed-off-by: John Molakvoæ <skjnldsv@protonmail.com>

2022-09-22 06:30 UTC, artonge approved these changes
Which context can this happen?

2022-09-22 06:31 UTC, artonge requested changes

2022-09-22 06:31 UTC, artonge commented on src/views/AlbumContent.vue
> +					.map(file => file.fileid.toString())
That's wrong, the veritable will contain files and not file ids

2022-09-22 06:32 UTC, artonge approved these changes

2022-09-22 10:18 UTC, skjnldsv commented
> Which context can this happen?

File put to trashbin

2022-09-22 11:00 UTC, skjnldsv commented
/compile amend /

2022-09-22 13:27 UTC, skjnldsv commented
/backport to stable25

2022-09-22 14:07 UTC, artonge approved these changes

2022-09-23 07:30 UTC, merged

2022-09-23 07:31 UTC, skjnldsv commented
/backport to stable25