Add always visible new album labels
nextcloud/photos pull request #1771
Opened 2023-05-04 01:40 UTC by Pytal

Before | After
--- | ---
![image](https://user-images.githubusercontent.com/24800714/236090492-ce31f734-601a-42f9-99cb-a381a0b8cb7e.png) | ![image](https://user-images.githubusercontent.com/24800714/236090499-73270f17-aa83-4f9a-827c-ea39d9aea13d.png)

2023-05-04 01:41 UTC, Pytal commented
/compile amend /

2023-05-04 07:03 UTC, JuliaKirschenheuter approved these changes

2023-05-04 07:35 UTC, szaimen approved these changes
LGTM but didnt test

2023-05-04 08:24 UTC, artonge requested changes
Can you align the MapMarker icon? Either with the text or the input field.

2023-05-05 01:36 UTC, Pytal commented
/compile amend /

2023-05-05 06:19 UTC, artonge approved these changes

2023-05-05 06:20 UTC, merged