fix(migrations): duplicated preference
nextcloud/photos pull request #2571
Opened 2024-08-02 12:43 UTC by Altahrim

Fix #2570

2024-08-02 12:59 UTC, nickvergessen requested changes
Missing version bump in info.xml to execute the migration on deployment

2024-08-02 13:02 UTC, Altahrim commented on lib/Migration/Version30000Date20240417075404.php
> +			->set('configvalue', $update->func()->concat($update->expr()->literal('["'), 'configvalue', $update->expr()->literal('"]')))
Agree :) 
This part was already in the migration, I preferred to avoid changing it.

2024-08-02 14:34 UTC, nickvergessen commented on lib/Migration/Version30000Date20240417075404.php
> +			->set('configvalue', $update->func()->concat($update->expr()->literal('["'), 'configvalue', $update->expr()->literal('"]')))
If you are scared whether it works, createParameter does work in concat.
As said literal could break or result in unexpected things, e.g. with oracle
https://github.com/nextcloud/spreed/blob/0663e0f66227615f3ccee23cfc460ad3a4f7394a/lib/Migration/Version19000Date20240709183938.php#L43

2024-08-05 08:58 UTC, AndyScherzinger approved these changes

2024-08-05 09:46 UTC, Altahrim commented on lib/Migration/Version30000Date20240417075404.php
> +			->set('configvalue', $update->func()->concat($update->expr()->literal('["'), 'configvalue', $update->expr()->literal('"]')))
I made the change :)

2024-08-05 10:08 UTC, come-nc approved these changes

2024-08-06 08:25 UTC, merged